package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/go-openapi/errors"
)

/*ActualLRPNetInfo actual l r p net info

swagger:model ActualLRPNetInfo
*/
type ActualLRPNetInfo struct {

	/* address
	 */
	Address string `json:"address,omitempty"`

	/* ports
	 */
	Ports []*PortMapping `json:"ports,omitempty"`
}

// Validate validates this actual l r p net info
func (m *ActualLRPNetInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePorts(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ActualLRPNetInfo) validatePorts(formats strfmt.Registry) error {

	if swag.IsZero(m.Ports) { // not required
		return nil
	}

	for i := 0; i < len(m.Ports); i++ {

		if swag.IsZero(m.Ports[i]) { // not required
			continue
		}

		if m.Ports[i] != nil {

			if err := m.Ports[i].Validate(formats); err != nil {
				return err
			}
		}

	}

	return nil
}
