package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*PortMapping port mapping

swagger:model PortMapping
*/
type PortMapping struct {

	/* constainer port
	 */
	ConstainerPort int32 `json:"constainer_port,omitempty"`

	/* host port
	 */
	HostPort int32 `json:"host_port,omitempty"`
}

// Validate validates this port mapping
func (m *PortMapping) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
