package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/cf-furnace/k8s-tps/lib/model"
)

/*LRPStatsOK OK

swagger:response lRPStatsOK
*/
type LRPStatsOK struct {

	// In: body
	Payload []*model.LRPInstance `json:"body,omitempty"`
}

// NewLRPStatsOK creates LRPStatsOK with default headers values
func NewLRPStatsOK() *LRPStatsOK {
	return &LRPStatsOK{}
}

// WithPayload adds the payload to the l r p stats o k response
func (o *LRPStatsOK) WithPayload(payload []*model.LRPInstance) *LRPStatsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the l r p stats o k response
func (o *LRPStatsOK) SetPayload(payload []*model.LRPInstance) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *LRPStatsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*LRPStatsBadRequest Empty guid specified

swagger:response lRPStatsBadRequest
*/
type LRPStatsBadRequest struct {
}

// NewLRPStatsBadRequest creates LRPStatsBadRequest with default headers values
func NewLRPStatsBadRequest() *LRPStatsBadRequest {
	return &LRPStatsBadRequest{}
}

// WriteResponse to the client
func (o *LRPStatsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}

/*LRPStatsUnauthorized Unauthorized

swagger:response lRPStatsUnauthorized
*/
type LRPStatsUnauthorized struct {
}

// NewLRPStatsUnauthorized creates LRPStatsUnauthorized with default headers values
func NewLRPStatsUnauthorized() *LRPStatsUnauthorized {
	return &LRPStatsUnauthorized{}
}

// WriteResponse to the client
func (o *LRPStatsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
}

/*LRPStatsNotFound No process found for guid

swagger:response lRPStatsNotFound
*/
type LRPStatsNotFound struct {
}

// NewLRPStatsNotFound creates LRPStatsNotFound with default headers values
func NewLRPStatsNotFound() *LRPStatsNotFound {
	return &LRPStatsNotFound{}
}

// WriteResponse to the client
func (o *LRPStatsNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}

/*LRPStatsInternalServerError Failed fetching actual LRP info

swagger:response lRPStatsInternalServerError
*/
type LRPStatsInternalServerError struct {
}

// NewLRPStatsInternalServerError creates LRPStatsInternalServerError with default headers values
func NewLRPStatsInternalServerError() *LRPStatsInternalServerError {
	return &LRPStatsInternalServerError{}
}

// WriteResponse to the client
func (o *LRPStatsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
}
