package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/cf-furnace/k8s-tps/lib/model"
)

/*LRPStatusOK OK

swagger:response lRPStatusOK
*/
type LRPStatusOK struct {

	// In: body
	Payload []*model.LRPInstance `json:"body,omitempty"`
}

// NewLRPStatusOK creates LRPStatusOK with default headers values
func NewLRPStatusOK() *LRPStatusOK {
	return &LRPStatusOK{}
}

// WithPayload adds the payload to the l r p status o k response
func (o *LRPStatusOK) WithPayload(payload []*model.LRPInstance) *LRPStatusOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the l r p status o k response
func (o *LRPStatusOK) SetPayload(payload []*model.LRPInstance) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *LRPStatusOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*LRPStatusInternalServerError Failed fetching actual LRP info

swagger:response lRPStatusInternalServerError
*/
type LRPStatusInternalServerError struct {
}

// NewLRPStatusInternalServerError creates LRPStatusInternalServerError with default headers values
func NewLRPStatusInternalServerError() *LRPStatusInternalServerError {
	return &LRPStatusInternalServerError{}
}

// WriteResponse to the client
func (o *LRPStatusInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
}
